Repository The-world-only-knows-Winner/ORI-Server, pull requests merged in 2023-09, with the labels that each got.

#2 🔀 :: (#1) 프로젝트 세팅
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/todo.yaml
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  ori-application/build.gradle.kts
  ori-application/src/main/kotlin/com/onlywin/ori/.gitkeep
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/OriServerApplication.kt
  ori-infrastructure/src/main/resources/application.properties
  settings.gradle.kts
Labels: 프로젝트 세팅

#4 🔀 :: (#3) 어노테이션 세팅
  ori-application/src/main/kotlin/com/onlywin/ori/.gitkeep
  ori-application/src/main/kotlin/com/onlywin/ori/common/annotation/Aggregate.kt
  ori-application/src/main/kotlin/com/onlywin/ori/common/annotation/UseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/OriServerApplication.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/annotation/Adapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/annotation/config/AnnotationConfig.kt
Labels: 프로젝트 세팅

#6 🔀 :: (#5) User 엔티티 추가 및 MapStruct 의존성 및 CI 추가
  .editorconfig
  .github/workflows/CI.yml
  build.gradle.kts
  ori-application/src/main/kotlin/com/onlywin/ori/user/User.kt
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/entity/BaseUUIDEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/user/domain/UserEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/user/domain/UserMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/user/domain/UserRepository.kt
  ori-infrastructure/src/main/resources/application.properties
  ori-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#9 🔀 :: (#8) Swagger 세팅
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/swagger/SwaggerConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/healthcheck/HealthCheckWebAdapter.kt
  ori-infrastructure/src/main/resources/application.yml
Labels: 프로젝트 세팅

#14 🔀 :: (#12) Station 엔티티 생성
  ori-application/src/main/kotlin/com/onlywin/ori/station/Station.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/station/domain/StationEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/station/domain/StationMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/station/domain/StationRepository.kt
Labels: 기능 추가

#13 🔀 :: (#7) security 세팅
  ori-application/src/main/kotlin/com/onlywin/ori/common/error/ErrorProperty.kt
  ori-application/src/main/kotlin/com/onlywin/ori/common/error/OriException.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/dto/response/TokenResponse.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/model/RefreshToken.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/spi/JwtPort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/exception/UserNotFoundException.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/exception/error/UserErrorCode.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/model/User.kt
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/OriServerApplication.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/config/PropertiesScanConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/error/GlobalErrorCode.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/error/response/ErrorResponse.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/exception/ExpiredTokenException.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/exception/InvalidTokenException.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/filter/FilterConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/filter/GlobalExceptionFilter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/filter/JwtFilter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/redis/RedisConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/redis/RedisProperties.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/SecurityConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/auth/UserDetails.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/auth/UserDetailsService.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/jwt/JwtProperties.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/jwt/JwtTokenAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/jwt/JwtTokenParser.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/jwt/TokenType.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenRepository.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/persistence/UserEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/persistence/UserMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/persistence/UserRepository.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/route/domain/RouteEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/route/domain/RouteMapper.kt
  ori-infrastructure/src/main/resources/application.yml
Labels: 프로젝트 세팅

#18 🔀 :: (#17) Feign 설정
  ori-application/src/main/kotlin/com/onlywin/ori/common/error/ErrorProperty.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/spi/JwtPort.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/feign/FeignConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/feign/error/FeignErrorCode.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/feign/exception/FeignException.kt
Labels: 프로젝트 세팅

#21 🔀:: (#20) Ktlint 설정
  .editorconfig
  .github/workflows/CI.yml
  build.gradle.kts
Labels: 프로젝트 세팅

#24 🔀 :: (#23) 정류장 조회 기능 추가
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/spi/AuthCodePort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/station/dto/response/QueryStationList.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/station/spi/StationPort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/station/usecase/QueryStationUseCase.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/spi/UserPort.kt
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/exception/InternalServerErrorException.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/feign/FeignConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/feign/client/StationClient.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/feign/client/StationClientImpl.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/filter/GlobalExceptionFilter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/util/JsonUtil.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/AuthWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/persistence/RouteMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/station/persistence/StationMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/station/presentation/StationWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/UserWebAdapter.kt
  ori-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#26 🔀 :: (#25) 도커파일 및 CD 구축
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile
Labels: 프로젝트 세팅

#28 🔀 :: (#27) Redis 설정 수정 및 Jwt ENV 제거
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/redis/RedisConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/jwt/JwtProperties.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/jwt/JwtTokenParser.kt
  ori-infrastructure/src/main/resources/application.yml
Labels: chore

#30 🔀 :: (#29) Prometheus 설정
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/resources/application.yml
Labels: 프로젝트 세팅

#32 🔀 :: (#31) 버스 길찾기 api
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/dto/response/QueryRouteList.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/enums/TrafficType.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/spi/RoutePort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/usecase/QueryRouteUseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/presentation/RouteWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/FeignConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/client/route/RouteClient.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/client/route/RouteClientImpl.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/client/station/StationClient.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/client/station/StationClientImpl.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/error/FeignErrorCode.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/exception/FeignException.kt
Labels: 기능 추가

#34 🔀 :: (#33) Json 파싱 코드 리팩토링
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/usecase/QueryRouteUseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/presentation/RouteWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/UserWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/healthcheck/HealthCheckWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/client/route/RouteClientImpl.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/client/station/StationClientImpl.kt
Labels: chore, 리팩토링

#39 🔀 :: (#37) 내 정보 수정 기능 추가
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/User.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/dto/request/UpdateUserInfoRequest.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/spi/UserPort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/usecase/UpdateUserInfoUseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/dto/request/SendAuthCodeWebRequest.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/dto/request/VerifyAuthCodeWebRequest.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/persistence/UserPersistenceAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/UserWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/dto/request/SignUpWebRequest.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/dto/request/UpdateUserInfoWebRequest.kt
Labels: 기능 추가

#36 🔀 :: (#35) 로그아웃 기능 추가
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/exception/RefreshTokenNotFoundException.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/exception/error/AuthErrorCode.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/spi/RefreshTokenPort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/usecase/LogOutUseCase.kt
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/security/auth/UserDetails.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenPersistenceAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/AuthWebAdapter.kt
Labels: 기능 추가

#41 🔀 :: (#40) 마이페이지 조회 기능 추가
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/dto/response/QueryMyInfoResponse.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/usecase/QueryMyInfoUseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/UserWebAdapter.kt
Labels: 기능 추가
