Repository The-world-only-knows-Winner/ORI-Server, pull requests merged in 2023-10, with the labels that each got.

#42 🔀 :: (#38) 비밀번호 수정 기능 추가
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/dto/request/ChangePasswordRequest.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/exception/PasswordMisMatchException.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/exception/error/AuthErrorCode.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/usecase/ChangePasswordUseCase.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/User.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/AuthWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/dto/request/ChangePasswordWebRequest.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/dto/request/SignUpWebRequest.kt
Labels: chore, 기능 추가

#44 🔀 :: (#43) 토큰 재발급 기능 추가
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/spi/RefreshTokenPort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/usecase/TokenRefreshUseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenPersistenceAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/RefreshTokenRepository.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/presentation/AuthWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/station/presentation/StationWebAdapter.kt
Labels: 기능 추가

#47 🔀 :: (#46) 경로 설정 API
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/Route.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/dto/request/AddRouteRequest.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/spi/RoutePort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/usecase/AddRouteUseCase.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/station/Station.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/station/spi/StationPort.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/persistence/RoutePersistenceAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/presentation/RouteWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/presentation/dto/request/AddRouteWebRequest.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/station/persistence/StationPersistenceAdapter.kt
  ori-infrastructure/src/main/resources/application.yml
Labels: chore, 기능 추가, 리팩토링

#49 🔀 :: (#48) 즐겨찾기한 경로 조회 api
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/Route.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/dto/request/AddRouteRequest.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/dto/response/QueryMyRouteListResponse.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/spi/RoutePort.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/spi/vo/MyRouteListVO.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/usecase/AddRouteUseCase.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/route/usecase/QueryMyRouteListUseCase.kt
  ori-infrastructure/build.gradle.kts
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/common/config/QueryDslConfig.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/auth/persistence/AuthCodeMapper.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/persistence/RouteEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/persistence/RoutePersistenceAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/persistence/vo/QueryMyRouteListVO.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/presentation/RouteWebAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/presentation/dto/request/AddRouteWebRequest.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/persistence/UserMapper.kt
Labels: 기능 추가

#54 🔀 :: (#53) 로그인 API 에러 코드 변경
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/exception/EmailNotFoundException.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/exception/error/AuthErrorCode.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/auth/usecase/SignInUseCase.kt
Labels: chore

#56 🔀 :: (#55) User 엔티티 deviceToken 컬럼 제거
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/User.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/dto/request/SignUpRequest.kt
  ori-application/src/main/kotlin/com/onlywin/ori/domain/user/usecase/SignUpUseCase.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/persistence/UserEntity.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/user/presentation/dto/request/SignUpWebRequest.kt
Labels: chore

#58 🔀 :: (#57) 길찾기 error handling
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/domain/route/persistence/RoutePersistenceAdapter.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/error/FeignErrorCode.kt
  ori-infrastructure/src/main/kotlin/com/onlywin/ori/thirdparty/feign/exception/FeignException.kt
Labels: chore
